appointments/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^appointments/', include('apps.app_appt.urls',namespace='appointments')) ,
    url(r'^', include('apps.app_reglogin.urls',namespace='users')) 
]

apps/app_appt/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
    url(r'^dashboard$', views.dashboard , name ='dashboard'),
    url(r'^addappointment$', views.addappointment , name ='addappointment') ,
    url(r'^editappt/(?P<id>\d+)$$', views.editappt , name ='editappt') ,
     url(r'^deleteappt/(?P<id>\d+)$$', views.deleteappt , name ='deleteappt') ,
    url(r'^logout$', views.logout , name ='logout')  
 
    ]

apps/app_appt/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..app_reglogin.models import User
from django.db import models
from datetime import date
from datetime import datetime
import time 
import bcrypt

 
class appointmentManager(models.Manager):
    def addappointment(request,postData,sessiondata):
        print postData
        print " In addappointment %%%%%%%%%%%"
        
        results = {'status': True, 'errors': []}
        if not postData['tasks'] or len(postData['tasks'])<1:
            print "In tasks "
            results['status'] = False
            results['errors'].append("Please enter a task")

 
        if not postData['apptdate'] or len(postData['apptdate'])<1:
            print "In startdate "
            results['status'] = False
            results['errors'].append("Please enter an Appointment date")
        if not postData['appttime'] or len(postData['appttime'])<1:
            print "In returndate "
            results['status'] = False
            results['errors'].append("Please enter appointment time")

        if results['status']:   
            today = datetime.now().date()
            appdate = datetime.strptime(postData['apptdate'], '%Y-%m-%d').date()
            
       
            if appdate < today :  
                results['status'] = False
                results['errors'].append('Appointment Date must be in the future.')

            apptime = datetime.strptime(postData['appttime'], '%H:%S').time()
            currenttime = datetime.now().time()
            if  appdate == today and apptime < currenttime:  
                results['status'] = False
                results['errors'].append('Appointment Time   must be in the future.')




        if results['status']:
            user1 = User.objects.get(id = sessiondata['userid'])
            appointment1 = Appointment.objects.create(Tasks=postData['tasks'],
            apptdate=postData['apptdate'],appttime=postData['appttime'],apptuser = user1)
        
          
            results['status'] = True
            print "Added"
            #print apptdate.apptdate
       
        return results            

    def editappt(request,postData,sessiondata):
        print postData
        print " In editappt %%%%%%%%%%%"
        
        results = {'status': True, 'errors': []}
        if not postData['tasks'] or len(postData['tasks'])<1:
            print "In tasks "
            results['status'] = False
            results['errors'].append("Please enter a task")

 
        if not postData['apptdate'] or len(postData['apptdate'])<1:
            print "In startdate "
            results['status'] = False
            results['errors'].append("Please enter an Appointment date")



        if not postData['appttime'] or len(postData['appttime'])<1:
            print "In returndate "
            results['status'] = False
            results['errors'].append("Please enter appointment time")



        if results['status']:   
            today = datetime.now().date()
            appdate = datetime.strptime(postData['apptdate'], '%Y-%m-%d').date()
            
       
            if appdate < today :  
                results['status'] = False
                results['errors'].append('Appointment Date must be in the future.')

            apptime = datetime.strptime(postData['appttime'], '%H:%S').time()
            currenttime = datetime.now().time()
            if  appdate == today and apptime < currenttime:  
                results['status'] = False
                results['errors'].append('Appointment Time   must be in the future.')
 
        
        if results['status']:
            user1 = User.objects.get(id = sessiondata['userid'])
            appointment1 = Appointment.objects.get(id=sessiondata['apptid'])
            appointment1.apptdate = postData['apptdate'] 
            appointment1.appttime=postData['appttime']
            appointment1.Tasks=postData['tasks'] 
            appointment1.apptstatus=postData['apptstatus'] 
            appointment1.save()
             
        return results            






class Appointment(models.Model):
    Tasks = models.TextField(max_length=1000)
    apptdate =  models.DateField({'input_formats': ('%Y-%m-%d',)})
    appttime = models.TimeField()
    apptstatus = models.CharField(max_length=38,default = 'pending')
    apptuser= models.ForeignKey('app_reglogin.User', related_name="apptuser")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
     
    objects=appointmentManager()
    #bookauthors

apps/app_appt/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib import messages
from ..app_reglogin.models import User
from .models import Appointment
from django.core.urlresolvers import reverse
from datetime import date
from datetime import datetime
import time 
import bcrypt

# Create your views here.
def dashboard(request):
    #Tripschedule.objects.all().delete()
    #datetime.strptime(postData['startdate'], '%Y-%m-%d').date()
    today = datetime.now()
    print "today date"
    print today
    context = { 
                    'otherappts' :  Appointment.objects.all().exclude(apptdate=today),
                    'todayappt' :  Appointment.objects.filter(apptdate=today),
                    "name": request.session['name'],             
                    "userid" :  request.session['userid'] ,
                    "date" : datetime.today() 
                }
   
    return render(request,'app_appt/dashboard.html', context)


def addappointment(request):

    if request.method == "POST":
        print request.POST
        context = {
                "name": request.session['name'],
                "userid" :  request.session['userid'] 
                }
      
        result = Appointment.objects.addappointment(request.POST,context)
        print  result['status']
        if not result['status']:
             
            for error in result['errors']:
                messages.error(request,error)
                print "not added"
            return redirect(reverse('appointments:dashboard'))
        else: 
            messages.success(request,"Successful")
            return redirect(reverse('appointments:dashboard'))
            
    else:
            print "ENTERED GET"
            context = {
                    'appointment' :  Appointment.objects.all(),
                    "name": request.session['name']    
             }
    return render(request,'app_appt/dashboard.html',context )



def logout(request):
    request.session.clear()
    return redirect('users:my_index')


def editappt(request,id):
    if request.method == "POST":
        context = {
                "name": request.session['name'],
                "userid" :request.session['userid'],
                "apptid" : id
                }
        
        result = Appointment.objects.editappt(request.POST,context)
        print  result['status']
        if not result['status']:
             
            for error in result['errors']:
                messages.error(request,error)
                print "here"
                return redirect(reverse('appointments:editappt',kwargs={'id': id}))
        else: 
            messages.success(request,"Successful")
            return redirect(reverse('appointments:dashboard'))
    else:
        context = {
            'appt' :Appointment.objects.get(id=id)

            }
            #return redirect(reverse('show',kwargs={'id':id}))
    return render(request,'app_appt/editappt.html', context)

def deleteappt(request,id):
    Appointment.objects.filter(id=id).delete()
    return redirect(reverse('appointments:dashboard'))

apps/app_appt/templates/app_appt/dashboard.html
<!DOCTYPE html>
<html>
    <head>
       <title>Appointment Dashboard</title>
                 {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'app_appt/style/style.css' %}">
        
   
    </head>
    <body>
         <div id ="error" >
                {% if messages %}
            <ul class="messages">
                {% for message in messages %}
             
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
         </div>
        <p>
      <h1>Hello {{name}}!</h1>
      <a href = {% url 'appointments:logout'%}>Logout</a>
 
      <h4>Here are your appointments for today ,{{date}}  :</h4>
        <table style="width:50%">
            <tr>
                <th>Tasks</th>
                <th>Time</th>
                <th>Status </th>
                <th>Action </th>
            </tr> 
           
            {% for appt in todayappt %} 
                <tr>
                        <td>{{appt.Tasks}}</td>
                        <td>{{appt.appttime}}</td>
                        <td>{{appt.apptstatus}}</td> 
                     
                {% if appt.apptstatus == 'pending' or appt.apptstatus == 'missed'%}
                        <<td><a href={% url 'appointments:editappt' appt.id %} target="_blank">Edit</td>
                        <<td><a href={% url 'appointments:deleteappt' appt.id %} >Delete</td>
                {% endif %}        
                        
                     </tr>  
            {% endfor %}
        </table>  

        <h4> Your Other appointments:</h4>
                <table style="width:50%">
            <tr>
                <th>Tasks</th>
                <th>Date</th>
                <th>Time </th>
                
            {% for otherappt in otherappts %}
                <tr>
                        <td>{{otherappt.Tasks}}</td>
                        <td>{{otherappt.apptdate}}</td>
                        <td>{{otherappt.appttime}}</td>
                     </tr> 
            {% endfor %}
        </table> 

        <h4>Add Appointment</h4>
            <form action="{% url 'appointments:addappointment'%}" method ="post">
                {% csrf_token %}
                <p>
                <label for="apptdate">Date:</label>
                <input type="Date" id ="apptdate" name="apptdate">
                </p>
                <p>
                <label for="appttime">Time:</label>
                <input type="time" id ="appttime" name="appttime">
                </p>
                <p>
                <label for="tasks">Tasks:</label>
                <input type="text" id ="tasks" name="tasks">
                </p>
                <p><input id="submits" type="submit" value="Add"></p>
             </form>
           

apps/app_appt/templates/app_appt/editappt.html
<!DOCTYPE html>
<html>
    <head>
       <title>Update Appointment</title>
                 {% load staticfiles %}
            <link rel="stylesheet" href="{% static 'app_appt/style/style.css' %}">
        
   
    </head>
    <body>
         <div id ="error" >
                {% if messages %}
            <ul class="messages">
                {% for message in messages %}
             
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
         </div>
        <p>
      <h1>Hello {{name}}!</h1>
      <a href = {% url 'appointments:logout'%}>Logout</a>
      <a href = {% url 'appointments:dashboard'%}>dashboard</a>
             <form action="{% url 'appointments:editappt' appt.id%}" method ="post">
                {% csrf_token %}
                <p>
                <label for="apptdate">Date:</label>
                <input type="Date" id ="apptdate" name="apptdate" value= {{appt.apptdate}}>
                </p>
                <p>
                <label for="appttime">Time:</label>
                <input type="time" id ="appttime" name="appttime" value = {{appt.appttime}}>
                </p>
                <p>
                <label for="tasks">Tasks:</label>
                <input type="text" id ="tasks" name="tasks" value = {{appt.Tasks}}>
                </p>
                <p>
                Status : <select name="apptstatus">
                <option selected  >{{appt.apptstatus}}</option>
                <option value="done">done</option>
                <option value="pending">pending</option>
                <option value="missed">missed</option>

        </select>
 
                <p><input id="submits" type="submit" value="Update"></p>
             </form>